### ISSUE TITLE
Create an onboarding tutorial

### ISSUE THREAD

**Issue by weng271190436** [Azure/msi-acrpull#28]
something along the line of:
- create AKS cluster
- create MSI
- assign MSI to the VM/VMSS
- make all
- make docker-build
- make docker-push
- make deploy
- kubectl apply -f acrpullbinding_sample.yaml
- kubectl get secret test-msi-acrpull-secret -oyaml
- kubectl get serviceaccount default -oyaml

**Comment by stevekuznetsov** [comment]
This is now seen in the end-to-end test as of #71
