### ISSUE TITLE
Add support for Azure Workload Identity with managed identity

### ISSUE THREAD

**Issue by aramase** [Azure/msi-acrpull#45]
xref: https://azure.github.io/azure-workload-identity/docs/

Use workload identity federation with the managed identity for image pull.

**Comment by aramase** [comment]
It seems this is work in progress: https://github.com/Azure/msi-acrpull/pull/44

**Comment by stevekuznetsov** [comment]
I'll be taking this issue up!

**Comment by stevekuznetsov** [comment]
Fixed in #76
