### ISSUE TITLE
Use a CRD instead of a placeholder secret

### ISSUE THREAD

**Issue by samkreter** [Azure/msi-acrpull#5]
Using a CRD instead of annotations on a secret gives has these benefits:

Using a CRD instead of annotations on pull secrets is more straight forward for users, more easily extensible and allows us to watch only the resources we care about.

**Comment by weinong** [comment]
what secret are you referring to?

**Comment by samkreter** [comment]
The current implementation is using the imagePullSecret directly with a secret controller. We're moving this to use a CRD to manage the connections
